#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Alt" modifier is Mod1


# Enable touchpad tapping
riverctl input "pointer-1267-12579-ELAN0E04:00_04F3:3123_Touchpad" tap enabled

# Set keyboard layout options to swap Caps Lock and Escape keys
riverctl keyboard-layout -options "caps:swapescape" us

# Launch Waybar
riverctl spawn 'pgrep waybar || waybar'

# Launch Polkit authentication agent
riverctl spawn /usr/lib/mate-polkit/polkit-mate-authentication-agent-1


riverctl spawn 'dbus-update-activation-environment --systemd \
	WAYLAND_DISPLAY \
	QT_QPA_PLATFORM=wayland \
	XDG_CURRENT_DESKTOP=river \
	XDG_SESSION_DESKTOP=river \
	XDG_CURRENT_SESSION_TYPE=wayland \
	GDK_BACKEND="wayland,x11" \
	MOZ_ENABLE_WAYLAND=1 \
	_JAVA_AWT_WM_NONREPARENTING=1'

# Launch KDE Connect daemon
riverctl spawn kdeconnectd

# Launch dunst
riverctl spawn dunst

# Map Alt+Print to take a region screenshot and copy to clipboard
riverctl map normal Alt Print spawn 'slurp | grim -g - $(xdg-user-dir PICTURES)/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S.png) | wl-copy'

# Map Alt+Shift+A to launch PulseAudio Volume Control
riverctl map normal Alt+Shift A spawn pavucontrol

# Map Alt+Shift+N to launch nmtui in a floating terminal
riverctl map normal Alt+Shift N spawn 'alacritty --class floatingterm,floatingterm -e nmtui'

# Map Alt+Shift+B to launch bluetui in a floating terminal
riverctl map normal Alt+Shift B spawn 'alacritty --class floatingterm,floatingterm -e bluetui'

# Map Alt+Shift+L to lock the screen with swaylock
riverctl map normal Alt+Shift L spawn 'swaylock -feS --effect-blur 4x3 --effect-greyscale --indicator-radius 24 --indicator-thickness 8 --indicator-x-position 64 --indicator-y-position 64'

# Map Alt+Shift+Return to launch a terminal (Alacritty)
riverctl map normal Alt+Shift Return spawn alacritty

# Alt+Shift+P to start an instance of rofi
riverctl map normal Alt P spawn 'rofi -show combi -combi-modi drun,run -modi combi -show-icons'

# Alt+B to hide/unhide waybar
riverctl map normal Alt B spawn 'killall -SIGUSR1 waybar'

# Alt+Q to close the focused view
riverctl map normal Alt+Shift C close

# Alt+Shift+E to exit river
riverctl map normal Alt+Shift Q exit

# Alt+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Alt J focus-view next
riverctl map normal Alt K focus-view previous

# Alt+Period and Super+Comma to focus the next/previous output
riverctl map normal Alt Period focus-output next
riverctl map normal Alt Comma focus-output previous

# Alt+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Alt+Shift Period send-to-output next
riverctl map normal Alt+Shift Comma send-to-output previous

# Alt+Return to bump the focused view to the top of the layout stack
riverctl map normal Alt Return zoom

# Alt+H and Super+L to decrease/increase the main ratio of rivertile(1)
#riverctl map normal Alt H send-layout-cmd rivertile "main-ratio -0.05"
#riverctl map normal Alt L send-layout-cmd rivertile "main-ratio +0.05"

# Alt+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
#riverctl map normal Alt+Shift H send-layout-cmd rivertile "main-count +1"
#riverctl map normal Alt+Shift L send-layout-cmd rivertile "main-count -1"

# Super+{H,J,K,L} to move views
riverctl map normal Super H move left 100
riverctl map normal Super J move down 100
riverctl map normal Super K move up 100
riverctl map normal Super L move right 100

# Super+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Control H snap left
riverctl map normal Super+Control J snap down
riverctl map normal Super+Control K snap up
riverctl map normal Super+Control L snap right

# Super+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Shift H resize horizontal -100
riverctl map normal Super+Shift J resize vertical 100
riverctl map normal Super+Shift K resize vertical -100
riverctl map normal Super+Shift L resize horizontal 100

# Alt + Left Mouse Button to move views
riverctl map-pointer normal Alt BTN_LEFT move-view

# Alt + Right Mouse Button to resize views
riverctl map-pointer normal Alt BTN_RIGHT resize-view

# Alt + Middle Mouse Button to toggle float
#riverctl map-pointer normal Alt BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Alt+[1-9] to focus tag [0-8]
    riverctl map normal Alt $i set-focused-tags $tags

    # Alt+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Alt+Shift $i set-view-tags $tags

    # Alt+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Alt+Control $i toggle-focused-tags $tags

    # Alt+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Alt+Shift+Control $i toggle-view-tags $tags
done

# Alt+0 to focus all tags
# Alt+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Alt 0 set-focused-tags $all_tags
riverctl map normal Alt+Shift 0 set-view-tags $all_tags

# Alt+Space to toggle float
riverctl map normal Alt+Shift Space toggle-float

# Alt+F to toggle fullscreen
riverctl map normal Alt+Shift F toggle-fullscreen

# Alt+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Alt Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Alt Right send-layout-cmd rivertile "main-location right"
riverctl map normal Alt Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Alt Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Alt+F11 to enter passthrough mode
riverctl map normal Alt F11 enter-mode passthrough

# Alt+F11 to return to normal mode
riverctl map passthrough Alt F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume -l 1.0 @DEFAULT_SINK@ 0.05+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume -l 1.0 @DEFAULT_SINK@ 0.05-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'xbacklight -inc 5 -steps 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'xbacklight -dec 5 -steps 5'

    # Map Print to take a screenshot and copy to clipboard
    riverctl map $mode None Print spawn 'grim $(xdg-user-dir PICTURES)/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S.png) | wl-copy'
done

# Start mpvpaper with specific options to loop the wallpaper video
#riverctl spawn 'mpvpaper -fpo `--loop=inf --hwdec` "*" "$HOME/.loop"'

# Set the wallpaper image
riverctl spawn 'wbg "$HOME/.wall"'

# Set background and border color
riverctl background-color 0x0d0f18
riverctl border-color-focused 0xe7e8eb
riverctl border-color-unfocused 0x6a6a6a

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Window rules


riverctl rule-add ssd

riverctl rule-add -app-id 'org.pulseaudio.pavucontrol'  float
riverctl rule-add -app-id 'floatingterm'                float
riverctl rule-add -app-id 'localsend'                   float
riverctl rule-add -app-id 'galculator'                  float
riverctl rule-add -app-id 'Bitwarden'                   float
riverctl rule-add -app-id 'Gimp-2.10'                   float

riverctl rule-add -app-id 'Code'                        tags $((1 << 0))
riverctl rule-add -app-id 'neovide'                     tags $((1 << 0))
riverctl rule-add -app-id 'Gimp-2.10'                   tags $((1 << 1))
riverctl rule-add -app-id 'org.pipewire.Helvum'         tags $((1 << 1))
riverctl rule-add -app-id 'fr.handbrake.ghb'            tags $((1 << 1))
riverctl rule-add -app-id 'nemo'                        tags $((1 << 1))
riverctl rule-add -app-id 'foot'                        tags $((1 << 1))
riverctl rule-add -app-id 'firefox'                     tags $((1 << 2))
riverctl rule-add -app-id 'org.pwmt.zathura'            tags $((1 << 3))
riverctl rule-add -app-id 'marktext'                    tags $((1 << 3))
riverctl rule-add -app-id 'libreoffice'                 tags $((1 << 3))
riverctl rule-add -app-id 'thunderbird'                 tags $((1 << 4))
riverctl rule-add -app-id 'discord'                     tags $((1 << 4))
riverctl rule-add -app-id 'vesktop'                     tags $((1 << 4))
riverctl rule-add -app-id 'org.telegram.desktop'        tags $((1 << 4))
riverctl rule-add -app-id 'Spotify'                     tags $((1 << 5))
riverctl rule-add -app-id 'com.obsproject.Studio'       tags $((1 << 6))
riverctl rule-add -app-id 'org.qbittorrent.qBittorrent' tags $((1 << 6))
riverctl rule-add -app-id 'com.usebottles.bottles'      tags $((1 << 6))

# Set the default layout generator to be wideriver and start it.
# River will send the process group of the init executable SIGTERM on exit.

riverctl default-layout wideriver

wideriver \
    --layout left                              \
    --stack even                               \
    --ratio 0.55                               \
    --no-smart-gaps                            \
    --inner-gaps                   0           \
    --outer-gaps                   0           \
    --border-width                 1           \
    --border-width-monocle         0           \
    --border-color-focused         "0x93a1a1"  \
    --border-color-focused-monocle "0x93a1a1"  \
    --border-color-unfocused       "0x6a6a6a"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

# Map Alt+M to switch to monocle layout
riverctl map normal Alt m send-layout-cmd wideriver "--layout monocle"

# Map Alt+T to switch to left master layout
riverctl map normal Alt t send-layout-cmd wideriver "--layout left"

# Map Alt+L to increase the layout ratio
riverctl map normal Alt L send-layout-cmd wideriver "--ratio +0.05"

# Map Alt+H to decrease the layout ratio
riverctl map normal Alt H send-layout-cmd wideriver "--ratio -0.05"

# Map Alt+I to increase the count in the layout
riverctl map normal Alt I send-layout-cmd wideriver "--count +1"

# Map Alt+D to decrease the count in the layout
riverctl map normal Alt D send-layout-cmd wideriver "--count -1"

# Map Alt+Tab to focus previous tags
riverctl map normal Alt Tab focus-previous-tags
