# Colorscheme (hardhacker)

# Default colors
[colors.primary]
background = '#282433'
foreground = '#eee9fc'

# Normal colors
[colors.normal]
black   = '#282433'
red     = '#e965a5'
green   = '#b1f2a7'
yellow  = '#ebde76'
blue    = '#b1baf4'
magenta = '#e192ef'
cyan    = '#b3f4f3'
white   = '#eee9fc'

# Bright colors
[colors.bright]
black   = '#3f3951'
red     = '#e965a5'
green   = '#b1f2a7'
yellow  = '#ebde76'
blue    = '#b1baf4'
magenta = '#e192ef'
cyan    = '#b3f4f3'
white   = '#eee9fc'

[font]
size = 10.5

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'Bold'

[window]
opacity = 1.0

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 160
lines = 40
